= Citizen

An Private link:https://registry.terraform.io/[Terraform Module Registry]

image:https://travis-ci.org/outsideris/citizen.svg?branch=master["Build Status", link="https://travis-ci.org/outsideris/citizen"]
image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Foutsideris%2Fcitizen.svg?type=shield["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Foutsideris%2Fcitizen?ref=badge_shield"]
image:https://david-dm.org/outsideris/citizen/status.svg["Dependency Status", link="https://david-dm.org/outsideris/citizen"]
image:https://david-dm.org/outsideris/citizen/dev-status.svg["devDependency Status", link="https://david-dm.org/outsideris/citizen?type=dev"]

== Requirements
* Node.js 8+
* Support HTTPS - Terraform module registry only support HTTPS.

== Storage
Storage required to store modules files
There are multiple types of storage supported:

* File
** Environment variables needed to be set
*** `CITIZEN_STORAGE=file`
*** `CITIZEN_STORAGE_PATH=LOCAL_PATH_TO_STORE`
* S3
** Environment variables needed to be set
*** `CITIZEN_STORAGE=s3`
*** `CITIZEN_AWS_S3_BUCKET=YOUR_BUCKET_NAME`
*** `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

== Installation
set environment variables

[source, sh]
....
$ export HOSTNAME=YOUR_HOSTNAME
....

replace `YOUR_HOSTNAME` like `www.example.com:3000`.

== Build binaries

[source, sh]
....
$ npm run build
....

Under ``dist/``,
citizen binaries for linux, darwin and windows made.

== License
image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Foutsideris%2Fcitizen.svg?type=large["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Foutsideris%2Fcitizen?ref=badge_large"]
