#!/usr/bin/env sh

gpg --batch --gen-key << EOF
Key-Type: 1
Key-Length: 4096
Subkey-Type: 1
Subkey-Length: 4096
Name-Real: Test User
Name-Email: citizen@example.com
Expire-Date: 0
Passphrase: ""
EOF

gpg --list-keys