#!/usr/bin/env node
const request = require('request');
const { join } = require('path');
const fs = require('fs');
const { promisify } = require('util');
const unzipper = require('unzipper');
const debug = require('debug')('test:integration');

const chmod = promisify(fs.chmod);
const mkdir = promisify(fs.mkdir);
const access = promisify(fs.access);

const TERRAFORM_VERSION = process.argv.length === 3 ? process.argv[2] : '0.11.11';

const PLATFORM = process.platform;
const DOWNLOAD_URL = `https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${PLATFORM}_amd64.zip`;

const TARGET_DIR = join(__dirname, 'temp');

const download = async () => {
  try {
    await mkdir(TARGET_DIR);
  } catch (ignore) { }

  debug(`Start to download terraform v${TERRAFORM_VERSION}`);

  const terraformFile = join(TARGET_DIR, `terraform-${TERRAFORM_VERSION}`);
  debug('Will save terraform to %s', terraformFile);
  let notExist = true;
  try {
    notExist = await access(terraformFile);
  } catch (ignore) { }

  debug('Terraform file exists: %s', !notExist);
  return new Promise((resolve, reject) => {
    if (notExist) {
      debug('Downloading terraform from %s', DOWNLOAD_URL);
      request(DOWNLOAD_URL)
        .pipe(unzipper.Parse())
        .on('entry', (entry) => {
          debug('download completed');

          const fileName = entry.path;
          if (fileName === 'terraform') {
            debug('Write it as a file');
            entry.on('finish', async () => {
              await chmod(terraformFile, 0o765);
              debug('All done.');
              resolve();
            });
            entry.pipe(fs.createWriteStream(terraformFile));
          } else {
            entry.autodrain();
            reject(new Error('hahaha'));
          }
        });
    }

    debug('skip to download terraform');
    resolve();
  });
};

download();
